name: chkm8_app
description: CHKM8 - CheckMate

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+20

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  uuid: ^2.0.4
  intl: ^0.16.1
  equatable: ^1.1.1
  dio: ^3.0.10
  shared_preferences: ^0.5.8
  flutter_keyboard_visibility: ^3.2.1
  bloc: ^6.0.0
  flutter_bloc: ^6.0.0
  intl_phone_number_input: ^0.4.6+2
  firebase_messaging: ^7.0.0
  device_info: ^0.4.2+4
  overlay_support: ^1.0.5
  firebase_crashlytics: ^0.1.4+1
  connectivity: ^0.4.9+2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    #IMAGE_ASSET:
    - assets/images/bg_top_auth.png
    - assets/images/splash_image.png
    - assets/images/bg_verification_code_success.png
    - assets/images/ic_about_tabbar.png
    - assets/images/ic_notification_tabbar.png
    - assets/images/ic_home_tabbar.png
    - assets/images/ic_profile_tabbar.png
    - assets/images/bg_home.png
    - assets/images/ic_back.png
    - assets/images/ic_home_calendar.png
    - assets/images/ic_home_share.png
    - assets/images/ic_home_rate.png
    - assets/images/bg_Illustration_1.png
    - assets/images/bg_Illustration_2.png
    - assets/images/bg_Illustration_3.png
    - assets/images/bg_Illustration_4.png
    - assets/images/ic_edit_outline.png
    - assets/images/ic_arrow_right.png
    - assets/images/bg_change_my_phone_success.png
    - assets/images/ic_help_circle.png
    - assets/images/ic_help_circle_larger.png
    - assets/images/ic_copy_code.png
    - assets/images/ic_star_selected.png
    - assets/images/ic_star_unselected.png
    - assets/images/ic_group_one_star.png
    - assets/images/ic_group_two_star.png
    - assets/images/ic_group_three_star.png
    - assets/images/ic_group_four_star.png
    - assets/images/ic_group_five_star.png
    - assets/images/ic_extremely_safe.png
    - assets/images/ic_safe.png
    - assets/images/ic_neutral.png
    - assets/images/ic_unsafe.png
    - assets/images/ic_extremely_unsafe.png
    - assets/images/ic_arrow_down.png
    - assets/images/ic_arrow_up.png
    - assets/images/bg_schedule_invitation_confirmation.png
    - assets/images/bg_rating_step_one.png
    - assets/images/bg_rating_step_two.png
    - assets/images/bg_rating_step_three.png
    - assets/images/ic_uncheck.png
    - assets/images/ic_checked.png
    - assets/images/bg_rating_success.png
    - assets/images/bg_my_rating_inform.png
    - assets/images/bg_accept_invitation_success_screen.png
    - assets/images/ic_invitation_copy.png
    - assets/images/ic_close.png
    - assets/images/ic_schedule_copy.png
    - assets/images/ic_mars.png
    - assets/images/ic_transgender.png
    - assets/images/ic_woman.png
    - assets/images/ic_great.png
    - assets/images/ic_not_great.png
    - assets/images/ic_not_calendar.png
    - assets/images/bg_overall_not_happen.png

    #FILE_ASSETS
    - assets/resource/country_codes.json
    

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Muli
      fonts:
        - asset: assets/fonts/muli/Muli-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/muli/Muli-Light.ttf
          weight: 300
        - asset: assets/fonts/muli/Muli-Regular.ttf
          weight: 400
        - asset: assets/fonts/muli/Muli-Medium.ttf
          weight: 500
        - asset: assets/fonts/muli/Muli-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/muli/Muli-Bold.ttf
          weight: 700
        - asset: assets/fonts/muli/Muli-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/muli/Muli-Black.ttf
          weight: 900

    - family: Moderat
      fonts:
        - asset: assets/fonts/moderat/Moderat-Regular.ttf
          weight: 400

    - family: Sarabun
      fonts:
        - asset: assets/fonts/sarabun/Sarabun-Bold.ttf
          weight: 700

  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
