import 'package:chkm8_app/utils/constant.dart';
import 'package:chkm8_app/widgets/custom_navigation_bar.dart';
import 'package:flutter/material.dart';
import 'package:chkm8_app/utils/extension.dart';
import 'package:uuid/uuid.dart';

import '../../utils/extension/color_ext.dart';

class FAQScreen extends StatefulWidget {
  static final routeName = '/FAQScreen';

  const FAQScreen({Key key}) : super(key: key);

  @override
  _FAQScreenState createState() => _FAQScreenState();
}

class _FAQScreenState extends State<FAQScreen> {
  final List<_FAQObject> _dumpData = [
    _FAQObject(
        question: 'Why use ChkM8?',
        answer:
            'ChkM8 allows you to view the safety rating of someone before you meet. It shows you if a prospective date has a history of safe behavior, based on ratings from others. ChkM8\'s Request a Rating feature tells each user that a safety rating will take place after a date, which establishes boundaries of behavior for both parties.'),
    _FAQObject(
      question:
          'Do I have to share my safety rating before getting to see someone else’s? Does someone have to share their safety rating with me before seeing mine?',
      answer:
          'Yes, if you ask to see someone\'s rating, you must share your safety rating as well. ChkM8\'s safety rating exchange happens when one user invites another to enter a code generated by the system. When you disclose your safety rating, you can view the corresponding safety rating of the person you shared your rating with, in return.',
    ),
    _FAQObject(
      question: 'How do I remove \"Safe Without Ratings Provided?\"',
      answer:
          'The ChkM8 system is programmed to require at least three ratings before dropping the verbiage, "Without Ratings Provided." At least three scores are needed before incorporating the ChkM8 algorithm to provide a composite score and ensure your rating’s anonymity.',
    ),
    _FAQObject(
      question: 'How are the rating scores determined?',
      answer:
          'When determining a composite rating, ChkM8 uses only ratings provided by others who have had a date or meeting with the user. Rating calculations take into account various factors such as the ratings provided, the person\'s rating scheme, the number of ratings, and the time frame when the ratings were entered. All ratings remain in the user\'s account as long as the account exists.',
    ),
    _FAQObject(
      question: 'What is the advantage of using ChkM8\'s Full Service option?',
      answer:
          'ChkM8\'s Full Service option includes added features such as Integrity Ratings and Repeat Date Ratings, which give you more information to evaluate when considering a date. The Full Service option also provides you with the ability to defer rating your date before requesting another Rating to be scheduled, while ChkM8\'s free plan requires you to rate your experience before requesting another Scheduled Rating. The advantage of deferred ratings is that you are able to have more than one date in an 8-hour time frame.',
    ),
    _FAQObject(
      question: 'What is an Integrity Rating?',
      answer:
          'The Integrity Rating helps remove doubt about the truthfulness profiles by providing ratings about the accuracy of photos or stats shared in a user’s profile or elsewhere. The Integrity Rating can also be used to help confirm that any feedback provided about a date is true. This feature is available only with ChkM8\'s Full Service option.',
    ),
    _FAQObject(
      question: 'What is a Repeat Date Rating?',
      answer:
          'Repeat Date Rating is part of CkM8\'s Full Service option. The Repeat Date Rating shows how likely previous dates were to want to go on another date with the user. This feature can be used to win over someone by saying, "not only am I a safe date, but I\'m a fun date, too."',
    ),
    _FAQObject(
      question: 'How do I know the ratings I submit remain anonymous?',
      answer:
          'The app only requires your cell number and gender for registration. The app provides a window of time before sending the Rating Screens after your date is completed. This delay enables you to have privacy for rating. Any user\'s rating scores are based on a composite score, so a user\'s score cannot be directly attributed to your specific rating. Our Terms and Services/Privacy Policy detail how ChkM8 does not release any of its user\'s information unless demanded by a legal court order.',
    ),
    _FAQObject(
      question: 'Can any ChkM8 user rate me?',
      answer:
          'No. A user can only rate another user when an Invitation to Rate has been sent AND responded to with an agreement from the other user after your date. Full Service users can also share their Integrity and Repeat Date ratings if they so choose. But to rate another user requires agreement by way of using the Request to Rate invite feature.',
    ),
    _FAQObject(
      question:
          'What if someone rates me Unsafe and I disagree with that rating?',
      answer:
          'ChkM8 ratings are composite, so it\'s very difficult, if not impossible, to determine where any rating originated. When a user agrees to accept an invitation to Rate You Date, that user should understand the consequences of allowing their rating scores to be affected. ChkM8 is a Reputation Management system. The initial exchange of Safety Ratings is confirmation that you agree to use the Rate Your Date feature.',
    ),
  ];

  int _indexExp = -1;

  @override
  Widget build(BuildContext context) {
    return Container(
      height: double.infinity,
      decoration: BoxDecoration(
        image: DecorationImage(
          image: AssetImage('assets/images/bg_home.png'),
          fit: BoxFit.cover,
        ),
      ),
      child: Stack(
        children: <Widget>[
          CustomNavigationBar(
            navTitle: 'FAQ',
            isShowBack: false,
          ),
          Container(
            padding: EdgeInsets.only(
              top: CustomNavigationBar.heightNavBar +
                  context.media.viewPadding.top,
            ),
            child: ListView.separated(
              padding: const EdgeInsets.only(
                bottom: 80,
              ),
              itemBuilder: (ctx, idx) {
                return _buildCell(
                  _dumpData[idx],
                  _indexExp == idx,
                  () {
                    if (_indexExp == idx) {
                      _indexExp = -1;
                    } else {
                      _indexExp = idx;
                    }

                    setState(() {});
                  },
                );
              },
              separatorBuilder: (ctx, idx) {
                return Divider(
                  height: 0.5,
                  color: ColorExt.colorWithHex(0xE0E0E0),
                );
              },
              itemCount: _dumpData.length,
            ),
          ),
          // Positioned(
          //   bottom: 16,
          //   right: 16,
          //   child: CustomButtonWidget(
          //     title: 'Contact us',
          //     width: 128,
          //     onPressed: () {},
          //   ),
          // )
        ],
      ),
    );
  }

  Widget _buildCell(_FAQObject obj, bool isExpanded, Function onPressed) {
    return Container(
      key: ValueKey(obj.id),
      color: Colors.white,
      child: GestureDetector(
        onTap: onPressed,
        child: Stack(children: [
          Padding(
            padding: const EdgeInsets.symmetric(vertical: 18),
            child: Column(
              children: <Widget>[
                Padding(
                  padding: const EdgeInsets.symmetric(horizontal: 20),
                  child: Row(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: <Widget>[
                      Expanded(
                        child: RichText(
                          text: TextSpan(
                            text: 'Q: ',
                            style: context.theme.textTheme.headline5.copyWith(
                              fontSize: 16,
                              fontWeight: FontWeight.bold,
                              color: Constaint.defaultTextColor,
                            ),
                            children: [
                              TextSpan(
                                text: obj.question,
                                style:
                                    context.theme.textTheme.headline5.copyWith(
                                  fontSize: 16,
                                  color: Constaint.defaultTextColor,
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Container(
                        width: 27,
                        height: 27,
                      ),
                    ],
                  ),
                ),
                if (isExpanded) SizedBox(height: 10),
                if (isExpanded)
                  Container(
                    padding: const EdgeInsets.all(13),
                    margin: const EdgeInsets.symmetric(horizontal: 12),
                    decoration: BoxDecoration(
                      borderRadius: BorderRadius.circular(13),
                      color: ColorExt.colorWithHex(0xEFFAF5),
                    ),
                    child: Row(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: <Widget>[
                        Expanded(
                          child: RichText(
                            text: TextSpan(
                              text: 'A: ',
                              style: context.theme.textTheme.headline5.copyWith(
                                fontSize: 16,
                                fontWeight: FontWeight.bold,
                                color: Constaint.defaultTextColor,
                              ),
                              children: [
                                TextSpan(
                                  text: obj.answer,
                                  style: context.theme.textTheme.headline5
                                      .copyWith(
                                    fontSize: 16,
                                    color: Constaint.defaultTextColor,
                                  ),
                                ),
                              ],
                            ),
                          ),
                        ),
                        Container(
                          width: 27,
                          height: 27,
                        ),
                      ],
                    ),
                  ),
              ],
            ),
          ),
          Positioned(
            width: 27,
            height: 27,
            right: 20,
            top: 14,
            child: ImageIcon(
              AssetImage(
                (isExpanded)
                    ? 'assets/images/ic_arrow_up.png'
                    : 'assets/images/ic_arrow_down.png',
              ),
              size: 27,
            ),
          ),
        ]),
      ),
    );
  }
}

class _FAQObject {
  final String id = Uuid().v4();
  final String question;
  final String answer;

  _FAQObject({this.question, this.answer});
}
